mode: "online"              # online | offline
model_name: "gemini"
model_engine: "huggingface"
model_version: "gemini-2.5-flash"

db: "chromadb"               # qdrant | mongodb | chromadb
embedding_model: "Alibaba-NLP/gte-multilingual-base"
reranker: "Alibaba-NLP/gte-multilingual-reranker-base"
